name: Telegram bot builds successfully

on:
  pull_request:
    paths: [ 'telegram/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn workspace subid-telegram-bot install
      - run: yarn build:telegram
